### ISSUE TITLE
Ver guzzlehttp/guzzle ^7?

### ISSUE THREAD

**Issue by scorpsan** [vetheslav/smspby#1]
Problem 1
    - Root composer.json requires vetheslav/smspby ^0.0.5 -> satisfiable by vetheslav/smspby[0.0.5].
    - vetheslav/smspby 0.0.5 requires guzzlehttp/guzzle 6.* -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.5] but the package is fixed to 7.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by vetheslav** [comment]
Hi @scorpsan, thanks for your created issue. We'll update the library in a short period

**Comment by vetheslav** [comment]
It's updated. Thanks again
